FROM	node:16.15.0-alpine3.15
RUN 	mkdir -p /var/www/osase_fe
COPY 	. /var/www/osase_fe/.
WORKDIR /var/www/osase_fe/
RUN 	yarn install
#RUN yarn build --fix
CMD 	yarn serve --host 0.0.0.0 --port 8023
